# -*- coding: utf-8 -*-
"""py password new.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15nwthRy-kxt1kxiipvNou5GQjr9dszfj
"""

!pip install cryptography

!pip install python-firebase

from cryptography.fernet import Fernet

def generate_key():
    key = Fernet.generate_key()
    print(key)
generate_key()

import random
from firebase import firebase
chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}' #list of all charecters
website = input("Enter the website name:") 
username = input("Enter the username name:") 
length = int(input("Enter the length of password you want:"))  
password=''    
for c in range(length):
  password += random.choice(chars)   # generates the password for our desired length

# print(website)
# print(username)
print(password)

key = 'xwQ9yjhyztxAv26H3jH9mKCt3c2xlfdC8IINHc3pJZM='   #key generated rom our generate key func 
# key = 'JV4lxlylPSjkCqnbBgH768xakeBSPWF4sZ0zEXF2xto='

encoded_message = password.encode()
f = Fernet(key)
hashed = f.encrypt(encoded_message)

# print(hashed)
hashed = hashed.decode()
firebase = firebase.FirebaseApplication("https://passwordmanager-a9f93.firebaseio.com/", None)

data = {
  'username' : username,
  'website' : website,
  'hashpass' : hashed
}
result = firebase.put('user',username,data )

print(result)

from firebase import firebase

firebase = firebase.FirebaseApplication("https://passwordmanager-a9f93.firebaseio.com/", None)

userna = input("enter user name:")

result = firebase.get('https://passwordmanager-a9f93.firebaseio.com/user',userna)

encrypted_message = result['hashpass']

encrypted_message=bytes(encrypted_message,'utf-8')

decrypted_message = f.decrypt(encrypted_message)

print(decrypted_message.decode())